### ISSUE TITLE
Problem with linux-32 bit

### ISSUE THREAD

**Issue by megies** [obspy/anaconda-installers#3]
Trying to run tests on the built Anaconda installer for linux-32 bit is running into problems (e.g. https://travis-ci.org/obspy/anaconda-installers/jobs/253951756):

```
$ bash ../ObsPy*.sh -b -p $HOME/obspy-anaconda
PREFIX=/home/travis/obspy-anaconda
installing: python-2.7.13-0 ...
Python 2.7.13 :: Continuum Analytics, Inc.
installing: asn1crypto-0.22.0-py27_0 ...
installing: backports-1.0-py27_0 ...
installing: backports_abc-0.5-py27_0 ...
installing: basemap-1.0.7-np110py27_0 ...
[...]
installing: notebook-5.0.0-py27_0 ...
installing: numpy-1.10.4-py27_nomkl_2 ...
installing: obspy-1.0.3-py27_0 ...
installing: openblas-0.2.14-4 ...
installing: openssl-1.0.2l-0 ...
Traceback (most recent call last):
  File "/home/travis/obspy-anaconda/pkgs/.install.py", line 524, in <module>
    main2()
  File "/home/travis/obspy-anaconda/pkgs/.install.py", line 508, in main2
    post_extract()
  File "/home/travis/obspy-anaconda/pkgs/.install.py", line 447, in post_extract
    link(prefix, dist, linktype=None)
  File "/home/travis/obspy-anaconda/pkgs/.install.py", line 349, in link
    if not run_script(prefix, dist, 'post-link'):
  File "/home/travis/obspy-anaconda/pkgs/.install.py", line 254, in run_script
    import subprocess
  File "/home/travis/obspy-anaconda/lib/python2.7/subprocess.py", line 75, in <module>
    import pickle
  File "/home/travis/obspy-anaconda/lib/python2.7/pickle.py", line 1272, in <module>
    import binascii as _binascii
ImportError: libz.so.1: cannot open shared object file: No such file or directory
```

Need to check if just the installing doesn't work or if the built installer is broken too..

**Comment by megies** [comment]
It seems like building or at least testing installers on Travis 32bit won't work..
 - https://travis-ci.org/obspy/anaconda-installers/builds/254221839
 - https://travis-ci.org/obspy/anaconda-installers/jobs/254221841#L288
 - https://travis-ci.org/obspy/anaconda-installers/jobs/254221844#L257

We'll probably have to build installers for 32bit Linux using our docker setup..
